spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**, /users/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: MySuperSecretKeyThatIsLongEnough123456